name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: |
          echo "Starting npm ci..."
          npm ci --legacy-peer-deps
          echo "npm ci completed."
          
      - name: Build
        run: npm run build

      - name: Check Supabase Dependencies
        run: |
          echo "Checking for @supabase/supabase-js..."
          ls -la node_modules/@supabase || echo "Supabase directory not found"
          npm list @supabase/supabase-js || echo "Package not found in dependency tree" 